//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AddressBook.MAUI.LanguageResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    ///   This class was generated by MSBuild using the GenerateResource task.
    ///   To add or remove a member, edit your .resx file then rerun MSBuild.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Build.Tasks.StronglyTypedResourceBuilder", "15.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AddressBook.MAUI.LanguageResources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coming Soon....
        /// </summary>
        internal static string MESSAGE_ERROR_COMING_SOON {
            get {
                return ResourceManager.GetString("MESSAGE_ERROR_COMING_SOON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email or password..
        /// </summary>
        internal static string MESSAGE_ERROR_EMAIL_PASSWORD_ERROR {
            get {
                return ResourceManager.GetString("MESSAGE_ERROR_EMAIL_PASSWORD_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please insert all data..
        /// </summary>
        internal static string MESSAGE_ERROR_INSERT_ALL_DATA {
            get {
                return ResourceManager.GetString("MESSAGE_ERROR_INSERT_ALL_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter valid contact number.
        /// </summary>
        internal static string MESSAGE_ERROR_INVALID_CONTACT_NO {
            get {
                return ResourceManager.GetString("MESSAGE_ERROR_INVALID_CONTACT_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter valid email..
        /// </summary>
        internal static string MESSAGE_ERROR_INVALID_EMAIL {
            get {
                return ResourceManager.GetString("MESSAGE_ERROR_INVALID_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check your internet connection..
        /// </summary>
        internal static string MESSAGE_ERROR_NO_INTERNET {
            get {
                return ResourceManager.GetString("MESSAGE_ERROR_NO_INTERNET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your session is expired, Please login again..
        /// </summary>
        internal static string MESSAGE_ERROR_SESSION_EXPIRED {
            get {
                return ResourceManager.GetString("MESSAGE_ERROR_SESSION_EXPIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry! something went wrong..
        /// </summary>
        internal static string MESSAGE_ERROR_SOMETHING_WENT_WRONG {
            get {
                return ResourceManager.GetString("MESSAGE_ERROR_SOMETHING_WENT_WRONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry! something went wrong with the login process..
        /// </summary>
        internal static string MESSAGE_ERROR_SOMETHING_WENT_WRONG_WITH_USER_LOGIN {
            get {
                return ResourceManager.GetString("MESSAGE_ERROR_SOMETHING_WENT_WRONG_WITH_USER_LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Save successfully..
        /// </summary>
        internal static string MESSAGE_SUCCESS_DATA_SAVE {
            get {
                return ResourceManager.GetString("MESSAGE_SUCCESS_DATA_SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your data is updated..
        /// </summary>
        internal static string MESSAGE_SUCCESS_DATA_UPDATED {
            get {
                return ResourceManager.GetString("MESSAGE_SUCCESS_DATA_UPDATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact number goes here.
        /// </summary>
        internal static string PLACEHOLDER_CONTACT_NO {
            get {
                return ResourceManager.GetString("PLACEHOLDER_CONTACT_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email goes here.
        /// </summary>
        internal static string PLACEHOLDER_EMAIL {
            get {
                return ResourceManager.GetString("PLACEHOLDER_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password goes here.
        /// </summary>
        internal static string PLACEHOLDER_PASSWORD {
            get {
                return ResourceManager.GetString("PLACEHOLDER_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search name....
        /// </summary>
        internal static string PLACEHOLDER_SEARCH_CONTACT {
            get {
                return ResourceManager.GetString("PLACEHOLDER_SEARCH_CONTACT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name goes here.
        /// </summary>
        internal static string PLACEHOLDER_USERNAME {
            get {
                return ResourceManager.GetString("PLACEHOLDER_USERNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        internal static string TEXT_ACTIVE {
            get {
                return ResourceManager.GetString("TEXT_ACTIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string TEXT_ADD {
            get {
                return ResourceManager.GetString("TEXT_ADD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address Book.
        /// </summary>
        internal static string Text_ADDRESS_BOOK {
            get {
                return ResourceManager.GetString("Text_ADDRESS_BOOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string TEXT_CANCEL {
            get {
                return ResourceManager.GetString("TEXT_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Number.
        /// </summary>
        internal static string TEXT_CONTACT_NUMBER {
            get {
                return ResourceManager.GetString("TEXT_CONTACT_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string TEXT_DELETE {
            get {
                return ResourceManager.GetString("TEXT_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail.
        /// </summary>
        internal static string TEXT_DETAIL {
            get {
                return ResourceManager.GetString("TEXT_DETAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string TEXT_EMAIL {
            get {
                return ResourceManager.GetString("TEXT_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log In.
        /// </summary>
        internal static string TEXT_LOG_IN {
            get {
                return ResourceManager.GetString("TEXT_LOG_IN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string TEXT_LOGIN {
            get {
                return ResourceManager.GetString("TEXT_LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login with Facebook.
        /// </summary>
        internal static string TEXT_LOGIN_WITH_FACEBOOK {
            get {
                return ResourceManager.GetString("TEXT_LOGIN_WITH_FACEBOOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string TEXT_LOGOUT {
            get {
                return ResourceManager.GetString("TEXT_LOGOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string TEXT_NAME {
            get {
                return ResourceManager.GetString("TEXT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Contact.
        /// </summary>
        internal static string TEXT_NO_DATA {
            get {
                return ResourceManager.GetString("TEXT_NO_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string TEXT_OK {
            get {
                return ResourceManager.GetString("TEXT_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Or.
        /// </summary>
        internal static string TEXT_OR {
            get {
                return ResourceManager.GetString("TEXT_OR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string TEXT_PASSWORD {
            get {
                return ResourceManager.GetString("TEXT_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string TEXT_SAVE {
            get {
                return ResourceManager.GetString("TEXT_SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string TEXT_UPDATE {
            get {
                return ResourceManager.GetString("TEXT_UPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert.
        /// </summary>
        internal static string TITLE_ALERT {
            get {
                return ResourceManager.GetString("TITLE_ALERT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string TITLE_ERROR {
            get {
                return ResourceManager.GetString("TITLE_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string TITLE_SUCCESS {
            get {
                return ResourceManager.GetString("TITLE_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation Error.
        /// </summary>
        internal static string TITLE_VALIDATION_ERROR {
            get {
                return ResourceManager.GetString("TITLE_VALIDATION_ERROR", resourceCulture);
            }
        }
    }
}
